version: "3"

services:
  node:
    image: chainify/substrate-nolik-dev:0.1.3-dev
    container_name: nolik-node
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    tty: true
    stdin_open: true
    command: bash -c "./target/release/node-nolik --ws-external --base-path /tmp/alice --chain local --alice --node-key 0000000000000000000000000000000000000000000000000000000000000001 --validator --rpc-methods=unsafe"

  ipfs:
    image: ipfs/go-ipfs
    container_name: nolik-ipfs
    volumes:
      - ~/.ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    tty: true
    stdin_open: true
